'use strict';

module.exports = {
	ACKNOWLEDGE_ERROR: 'ACKNOWLEDGE_ERROR',
	SET_DESIRED_DEVICE_TYPE: 'SET_DESIRED_DEVICE_TYPE',
	SELECT_DEVICE: 'SELECT_DEVICE',
	SET_SUPPORTED_DEVICES: 'SET_SUPPORTED_DEVICES',
	UPDATE_DETECTED_DEVICES: 'UPDATE_DETECTED_DEVICES',
	OPEN_DEVICE_ERROR: 'OPEN_DEVICE_ERROR'
};
